import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import { TranslationProvider } from "@/context/language-context";

const geistMono = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  display: 'swap',
  weight: ['300', '400', '700', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased`}
      >
        <TranslationProvider>
          {children}
        </TranslationProvider>
      </body>
    </html>
  );
}
